version: '3.4'
services:
  relaylog:
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app
    tty: true

  nats-streaming:
    image: nats-streaming:latest
    command: -p 4223 -m 8223 -cid fishapp-cluster -st FILE --dir /nats-streaming-data
    ports:
      - 8223:8223

volumes:
  nats-streaming-data:
networks:
  default:
    external:
      name: fishapp-net
